create database Casino;

go 

use Casino;

create table dbo.EMPLOYEE (
	EMP_ID int NOT NULL IDENTITY(1,1) PRIMARY KEY,
	EMP_NAME varchar(50) NOT NULL,
	EMP_ADDRESS varchar(150),
	EMP_DOB DATE,
	EMP_HIRE_DATE DATE NOT NULL,
	EMP_FIRE_DATE DATE,
	EMP_DEPART_DATE DATE,
	EMP_LOCKER int,
	EMP_PAY_RATE int NOT NULL,
	EMP_VACATION_ENTITLEMENT int,
	EMP_SICK_DAYS_ENTITLEMENT int
);
	
create table dbo.WRITTEN_WARNING (
	WW_ID int NOT NULL IDENTITY(1,1),
	EMP_ID int FOREIGN KEY REFERENCES dbo.EMPLOYEE(EMP_ID),
	WW_DATE DATE NOT NULL,
	WW_OFFENCE varchar(150) NOT NULL,
	WW_LEVEL int NOT NULL,
	WW_STATUS varchar(50) NOT NULL,
	WW_COMMENTS varchar(350),
	CONSTRAINT PK_WRITTEN_WARNING PRIMARY KEY (WW_ID, EMP_ID)
)

select * from dbo.EMPLOYEE;
select * from dbo.WRITTEN_WARNING;
